---

localdev_user: "vagrant"
localdev_home: "/home/vagrant"
localdev_xauthority: "{{ localdev_home }}/.Xauthority"
localdev_xvfb_display: ":1"

localdev_accounts:
    - { user: "{{ edxapp_user}}", home: "{{ edxapp_app_dir }}",
        env: "edxapp_env", repo: "edx-platform" }

    - { user: "{{ forum_user }}",home: "{{ forum_app_dir }}",
        env: "forum_env", repo: "cs_comments_service" }

# Helpful system packages for local dev
local_dev_pkgs:
    - vim
    - emacs
    - xorg
    - openbox
